### ISSUE TITLE
developer Gazelle

### ISSUE THREAD

**Issue by EugHDF** [WhatCD/Gazelle#108]
Hello,

I am new here and do not know how to get in touch with people so I pass by here.

I am on a project of bittorrent tracker under Gazelle.
We need a developer to finalize our project.
Can you help us or inform someone who could do it.

Thanks in advance.

(I am from Belgium and speaks French / use of google translate for translation)

EugHDF
x265@protonmail.com

**Comment by Edward-Stryfe** [comment]
The software was initially developed for a website, what.cd however the site has since been shutdown so I do not believe that there are any of the original developers who can help you. You can try going through some of the older files and seeing who made the last commit and messaging them however. 

Le logiciel a été initialement développé pour un site Web, what.cd cependant le site a été depuis l'arrêt donc je ne crois pas qu'il ya des développeurs d'origine qui peuvent vous aider. Vous pouvez essayer de parcourir certains des fichiers les plus anciens et voir qui a fait le dernier commit et de messagerie cependant.

**Comment by EugHDF** [comment]
@Edward-Stryfe
Thank you for the information.
My site is online if you want an invitation send a message to this address

contact@hdf.world
